version: '3'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stm_db
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db
    depends_on:
      - db
    command: ./initialize.sh npm start
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:root@db/stm_db
      - TOKEN_SECRET='7053b387979b7a08bd482b984851ecf9138d27a6087807ab93069a17bd871dfb'
      - GOOGLE_SECRET='SyXmZcdT6vPFeqcs0jaPhdVP'
