export const USER_ROLES = {
  REGULAR_USER: 'REGULAR_USER',
  USER_MANAGER: 'USER_MANAGER',
  ADMIN_USER: 'ADMIN_USER'
}

export const ACCESS_ROLES = {
  CAN_MANAGE_USER: [
    USER_ROLES.USER_MANAGER,
    USER_ROLES.ADMIN_USER
  ],
  CAN_CRUD_USER_JOBS: [
    USER_ROLES.ADMIN_USER
  ]
}